# bot
bot.token=# ???????? ????? ?????????

# openai.api
openai.api.key=# ???????? ????? GPT API
openai.api.transcription.url=https://api.openai.com/v1/audio/transcriptions
openai.api.transcription.model=whisper-1
openai.api.transcription.language=ru
openai.api.chat.url=https://api.openai.com/v1/chat/completions
openai.api.chat.model=gpt-4